# -- propiedades mail desarrollo y test
email.host=dom.sahost.com
email.from=info_sicel@acha.org.ar
email.user=info_sicel@acha.org.ar
email.password=
email.auth=false


# -- nuevo usuario --
email.signUpSubject=Bienvenido a ACHA.
#email.signUpTextBody= <BR><SPAN style="color:black;">Ahora usted puede ingresar a nuestro sitio http://clientes.most.com.ar/acha/sicel3/</SPAN><BR>
#email.signUpTextBody= <BR><SPAN style="color:black;">Ahora usted puede ingresar a nuestro sitio http://sicel.sahost.com/</SPAN><BR>
email.signUpHtmlBody1=<SPAN style="color:blue;">Usuario es: </SPAN>
email.signUpHtmlBody2=<BR><SPAN style="color:blue;">Clave es:    </SPAN>
email.signUpHtmlBody3=<BR><SPAN style="color:blue;">El Identificador es:    </SPAN>
email.signUpHtmlBody4=<BR><SPAN style="color:blue;">El link de la aplicación es:    </SPAN>
email.signUpHtmlBody5=<BR><SPAN style="color:blue;">Para leer la documentacion de la aplicacion, dirijase al menu desplegable, y en la primer opcion (Inicio) existe la documentacion.</SPAN>

# -- cargaMasivaPedrigree --
email.cargaMasivaSubject=Carga masiva Pedrigree
email.cargaMasivaRPSubject=Carga masiva Cambio de Rp y Tambo
email.cargaMasivaNombreArchivo=<BR><SPAN style="color:black;">Nombre del archivo: </SPAN>
email.cargaMasivaOk=<BR><SPAN style="color:blue;">Se cargaron correctamente: </SPAN>
email.listaErrores=<BR><SPAN style="color:red;">Se encontraron los siguientes errores: </SPAN>


# -- error de procesamiento

error.procesamiento.subject = Problemas con el Procesamiento del Lote
error.procesamiento.problema = <BR>Inconveniente encontrado\: 
error.procesamiento.fechaEnvio = <BR>Fecha de envio del lote\:  
error.procesamiento.usuario = <BR>Usuario\: 
error.procesamiento.numeroLote = <BR>Numero de Lote\: 
error.procesamiento.nombreArchivoProcesado = <BR>Nombre del archivo que se cargo para procesar:

# -- edición tambo --
email.nuevoTamboSubject=Nuevo tambo informado con identificador
email.modificacionTamboSubject=Modificación de tambo con identificador
email.edicionTamboTextBody= <BR><SPAN style="color:black;">Los datos del tambo son:</SPAN><BR>
email.edicionTamboHtmlBody1=<SPAN style="color:blue;">Identificador del Tambo: </SPAN>
email.edicionTamboHtmlBody2=<BR><SPAN style="color:blue;">Nombre:    </SPAN>
email.edicionTamboHtmlBody3=<BR><SPAN style="color:blue;">Nombre del Establecimiento al que pertenece:    </SPAN>
email.edicionTamboHtmlBody4=<BR><SPAN style="color:blue;">Metodo de control asignado:    </SPAN>
email.edicionTamboHtmlBody6=<BR><SPAN style="color:blue;">Centro de Computos:    </SPAN>
email.edicionTamboHtmlBody7=<BR><SPAN style="color:blue;">Identificador de Establecimiento:    </SPAN>
email.edicionTamboHtmlBody8=<BR><SPAN style="color:blue;">Identificador de Propietario:    </SPAN>
email.edicionTamboHtmlBody9=<BR><SPAN style="color:blue;">Nombre de Propietario:    </SPAN>
email.edicionTamboHtmlBody5=<BR><SPAN style="color:blue;">Activo?:    </SPAN>
email.edicionTamboHtmlBody10=<BR><SPAN style="color:blue;">Eclo del tambo:    </SPAN>
# -- edición tambo --
email.nuevoPropietarioSubject=Nuevo propietario informado, n\u00FAmero 
email.modificacionPropietarioSubject=Modificación de datos del propietario, número
email.edicionPropietarioTextBody= <BR><SPAN style="color:black;">Los datos del propietario son:</SPAN><BR>
email.edicionPropietarioHtmlBody1=<SPAN style="color:blue;">Identificador: </SPAN>
email.edicionPropietarioHtmlBody2=<BR><SPAN style="color:blue;">Nombre:    </SPAN>
email.edicionPropietarioHtmlBody3=<BR><SPAN style="color:blue;">Activo?:    </SPAN>
email.edicionPropietarioHtmlBody4=<BR><SPAN style\="color\:blue;">Numeros de SRA activos\:    </SPAN>

email.cambioAnimalSubject=Cambio de registro de animal
email.cambioAnimalTituloHtmlBody=Datos del animal:
email.cambioAnimalRPHtmlBody=<BR><SPAN style="color:black;">RP:</SPAN>
email.cambioAnimalNombreHtmlBody=<BR><SPAN style="color:black;">Nombre del animal:</SPAN>
email.cambioAnimalTamboHtmlBody=<BR><SPAN style="color:black;">Id Tambo:</SPAN>
email.cambioAnimalRegAnteriorHtmlBody=<BR><SPAN style="color:black;">Registro anterior:</SPAN>
email.cambioAnimalRegNuevoHtmlBody=<BR><SPAN style\="color\:black;">Registro nuevo\:</SPAN><BR>