######################
### Query Language ###
######################

## define query language constants / function names

hibernate.query.substitutions true 1, false 0, yes 'Y', no 'N'

#################
### Platforms ###
#################

## Server Used


hibernate.dialect=org.hibernate.dialect.Oracle10gDialect


# The Oracle JDBC driver doesn't like prepared statement caching very much.
#hibernate.statement_cache.size=0

# After a while, Oracle throws this exception: too many open cursors
# Disable PreparedStatement caching for the connection pool too.
# http://www.hibernate.org/120.html#A10
#hibernate.dbcp.ps.maxIdle = 0

# Stoping hibernate from using the column-names in queries to retrieve data from the resultsets
# More info in http://www.jroller.com/page/dashorst?entry=hibernate_3_1_something_performance1
#hibernate.jdbc.wrap_result_sets=true



#hibernate.connection.url = jdbc:firebirdsql:sicel/3050:/opt/database/sicel3.fdb
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:C:/Archivos de programa/Firebird/Firebird_2_0/databases/SICEL3.FDB
#en sicelmigrada estoy corriendo a syscord
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:C:/Archivos de programa/Firebird/Firebird_2_0/databases/SICEL3.FDB
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/databaseSicel/BASE completa con todos los scripts/SICEL3.FDB
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/databaseSicel/BASE completa con todos los scripts/s3/sicel3.fdb
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/Nueva carpeta (2)/11-11/sicel3.fdb
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/Nueva carpeta (2)/sicel3.fdb.2008-11-10/sicel3.fdb
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/Nueva carpeta (2)/sicel3Migracion.fdb


#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/nueva migracion/SICEL3MIGRACION.FDB
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/nueva migracion/SICEL3-2009-03-19.FDB
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/nueva migracion/SICEL3-2009-04-20.FDB
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/nueva migracion/SICEL3-2009-05-14.FDB
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/nueva migracion/SICEL3-2009-06-08.FDB
#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:D:/nueva migracion/SICEL3-2009-07-02.FDB

#hibernate.connection.url = jdbc:firebirdsql:localhost/3050:C:/sicel/compu/SICEL3.FDB
#hibernate.connection.url = jdbc:firebirdsql:acha/3050:/opt/database/sicel3.fdb
#hibernate.connection.url = jdbc:firebirdsql:makalu/3050:/opt/database/sicel3.fdb


#hibernate.connection.username SYSDBA
#hibernate.connection.password masterkey
#hibernate.connection.username USR_ACHA
#hibernate.connection.password omegslll     
#hibernate.connection.username USR_ACHA
#hibernate.connection.password agu7uz3u
#hibernate.connection.autoReconnect true
#hibernate.connection.is-connection-validation-required true
#hibernate.use_outer_join=true
hibernate.connection.charset = ISO8859_1
hibernate.connection.lc_ctype = ISO8859_1


###################################
### C3PO Connection Pool ###
###################################

hibernate.c3p0.min_size=5
hibernate.c3p0.max_size=15
hibernate.c3p0.timeout=600
hibernate.c3p0.max_statements=0

#################################
### Plugin ConnectionProvider ###
#################################

hibernate.connection.factory_class=org.hibernate.transaction.JDBCTransactionFactory
		
##############################
### Miscellaneous Settings ###
##############################

## print all generated SQL to the console

hibernate.show_sql false

## specify a JDBC isolation level
hibernate.connection.isolation 2
## Repeteable Read
## hibernate.connection.isolation 4
## Serializable
## hibernate.connection.isolation 8

## set the maximum JDBC 2 batch size (a nonzero value enables batching)

hibernate.jdbc.batch_size 0

## use streams when writing binary types to / from JDBC

hibernate.jdbc.use_streams_for_binary true

## set the maximum depth of the outer join fetch tree

hibernate.use_outer_join true
hibernate.max_fetch_depth 10

## enable CGLIB reflection optimizer (enabled by default)

hibernate.cglib.use_reflection_optimizer true\t\t
		
##########################
### Second-level Cache ###
##########################

## enable the query cache
hibernate.cache.use_query_cache=false
hibernate.cache.use_minimal_puts=false

## choose a cache implementation
hibernate.cache.provider_class=org.hibernate.cache.EhCacheProvider
