src.dir=src/main
web.dir=webapp
compile.outdir=target/classes
web.outdir=target/web
javadoc.outdir=target/docs
compileProd.outdir=targetProd/classes
webProd.outdir=targetProd/web
javadocProd.outdir=targetProd/docs
devlib.dir=dev-lib
#disableJalopy